### ISSUE TITLE
webAPI実装

### ISSUE THREAD

**Issue by TakumiFunasaka** [team-GJA/EarthQuakeSimulator#13]

**Comment by TakumiFunasaka** [comment]
go run main.go でlocalhost:8080
/ にアクセス→ファイルサーバーモード
/json に jsonファイルPOST → JSONが返ってくる

**Comment by TakumiFunasaka** [comment]
POST例
curl -v -H "Content-Type: application/json" -X POST -d '{"observation": {"lat": 37.7664995, "long": 141.0643965}, "epicenter": { "lat": 36.0995126, "long": 140.095151, "magnitude": 7.3}}' http://localhost:8080/json

**Comment by TakumiFunasaka** [comment]
HTTPヘッダに "Content-Type: application/json"を入れるのを忘れずに

**Comment by TakumiFunasaka** [comment]
返ってくるデータ
{"Status":0,"Result":"default","Scale":4.7060504,"Scaleranges":[1074,867,660,452,245,38,0,0]}

**Comment by applepine1125** [comment]
画像とtipsについても含めた返却データも考えといて

**Comment by TakumiFunasaka** [comment]
api仕様変更

/にアクセスプロジェクトルートを表示
/template/map.htmlでトップ画面、あとで直す予定

/sim/auto/ にPOST autoモードでjsonを返す
/sim/manual にPOST manualモードでjsonを返す

POST例
curl -v -H "Content-Type: application/json" -X POST -d '{"observation": {"pos": {"lat": 37.7664995, "long": 141.0643965}}, "epicenter": {"pos":{"lat": 36.0995126, "long": 140.095151}, "mag": 7.3 }}' http://localhost:8080/sim/auto

返ってくるデータ例
{
"Status":0,
"Result":"autoモードでアクセスを受けました",
"Scale":8.225528,
"Scaleranges":[1804,1596,1389,1182,975,767,560,353],
"Observation":{
"lat":37.7665,
"long":141.06439
},
"Epicenter":{
"lat":36.099514,
"long":140.09515
}
}

**Comment by TakumiFunasaka** [comment]
curl -v -H "Content-Type: application/json" -X POST -d '{"observation": {"pos": {"lat": 37.7664995, "lng": 141.0643965}}, "epicenter": {"pos":{"lat": 36.0995126, "lng": 140.095151}, "mag": 7.3 }}' http://localhost:8080/sim/auto

**Comment by TakumiFunasaka** [comment]
json仕様変更 Tips 追加

{"Status":0,"Result":"autoモードでアクセスを受けました","Scale":"0","Scaleranges":[0,0,0,0,0,0,0,0,0],"Observation":{"lat":37.7665,"lng":141.06439},"Epicenter":{"lat":36.099514,"lng":140.09515},"Tips":"キ
ッチンの火を急いで止めに行くとけがをする恐れがありますので、揺れが収まってから火を消しに行きましょう。"}
