### ISSUE TITLE
要件定義

### ISSUE THREAD

**Issue by TakumiFunasaka** [team-GJA/EarthQuakeSimulator#5]
DB関連の設計、その他もろもろ

**Comment by applepine1125** [comment]
フロントから観測点，震源，マグニチュード，深さのパラメータを投げるAPI
POST hogehoge

Json
{
  "observation": [{
    "lat": 緯度(double? float?),
    "long": 経度(double? float?)
  }], 
  "epicenter":[{
    "lat": 緯度,
    "lang": 経度,
    "magnitude":7.3,
    "depth" 900 (単位はkm)　　
  }]
}

**Comment by applepine1125** [comment]
サーバーからフロントへ計算結果等を投げるAPI
{
"result": [{
........
}]
}

**Comment by applepine1125** [comment]
結果出力時の付加情報をどうするかによってサーバーからのデータ内容は変わるので早急に決める

**Comment by TakumiFunasaka** [comment]
{"observation”: {"lat": 37.7664995, "long": 141.0643965 }, "epicenter”: {"lat": 36.0995126, "lang": 140.095151, "magnitude”:7.3, "depth”: 900 }}

**Comment by TakumiFunasaka** [comment]
{"observation”: {"lat": 37.7664995, "long": 141.0643965 }, "epicenter”: {"lat": 36.0995126, "lang": 140.095151, "magnitude”:7.3 }}

**Comment by TakumiFunasaka** [comment]
{
	"observation": {
		"lat": 37.7664995,
		"long": 141.0643965
	},
	"epicenter": {
		"lat": 36.0995126,
		"lang": 140.095151,
		"magnitude": 7.3
	}
}
